version: 2.1
aliases:
  - &defaults
    docker:
      - image: circleci/node:latest
    working_directory: ~/datrumvp

# Define the jobs we want to run for this project
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - persist_to_workspace:
          root: .
          paths:
            - .
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/datrumvp
      - run: npm run build
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/datrumvp
      - run: npm test

# Orchestrate our job run sequence
workflows:
  install_build_and_test:
    jobs:
      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - install
